version: 2

defaults: &defaults
  working_directory: /home/circleci/go-kit

golang: &golang
  <<: *defaults
  docker:
  - image: golang

golang-113: &golang-113
  <<: *defaults
  docker:
  - image: golang:1.13

golang-114: &golang-114
  <<: *defaults
  docker:
  - image: golang:1.14

golang-115: &golang-115
  <<: *defaults
  docker:
  - image: golang:1.15

golang-116: &golang-116
  <<: *defaults
  docker:
    - image: golang:1.16

golang-117: &golang-117
  <<: *defaults
  docker:
    - image: golang:1.17

jobs:
  modules:
    <<: *golang
    steps:
      - checkout
      - run:
          name: Make lock copy
          command: |
            cp go.mod go.mod.fix
            cp go.sum go.sum.fix
      - restore_cache:
          keys:
            - vendor-{{ checksum "go.mod.fix" }}-{{ checksum "go.sum.fix" }}
      - run:
          name: Install dependencies
          command: |
            echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
            if [ ! -e vendor ]; then
              go mod vendor
            fi
      - save_cache:
          key: vendor-{{ checksum "go.mod.fix" }}-{{ checksum "go.sum.fix" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths: '*'
  lint:
    <<: *golang
    steps:
    - attach_workspace:
        at: /home/circleci/go-kit
    - run:
        name: Go lint
        command: |
         go get -u golang.org/x/lint/golint
         make lint
    - run:
        name: Go vet
        command: |
         make vet
  test-go113:
    <<: *golang-113
    steps:
    - attach_workspace:
        at: /home/circleci/go-kit
    - run:
        name: Go Test
        command: |
          make test
  test-go114:
    <<: *golang-114
    steps:
    - attach_workspace:
        at: /home/circleci/go-kit
    - run:
        name: Go Test
        command: |
         make test
  test-go115:
    <<: *golang-115
    steps:
    - attach_workspace:
        at: /home/circleci/go-kit
    - run:
        name: Go Test
        command: |
          make test
  test-go116:
    <<: *golang-116
    steps:
      - attach_workspace:
          at: /home/circleci/go-kit
      - run:
          name: Go Test
          command: |
            make test
  test-go117:
    <<: *golang-117
    steps:
      - attach_workspace:
          at: /home/circleci/go-kit
      - run:
          name: Go Test
          command: |
            make test
  test-go117-with-race:
    <<: *golang-117
    steps:
      - attach_workspace:
          at: /home/circleci/go-kit
      - run:
          name: Go Test (With race checks)
          command: |
            make test-race

workflows:
  version: 2
  build-and-test:
    jobs:
    - modules
    - lint:
        requires:
          - modules
    - test-go113:
        requires:
        - modules
    - test-go114:
        requires:
        - modules
    - test-go115:
        requires:
        - modules
    - test-go116:
        requires:
          - modules
    - test-go117:
        requires:
          - modules
    - test-go117-with-race:
        requires:
          - modules
